[[redirects]]
  from = "/navpage.do/*"
  to = "https://dev16718.service-now.com/nav_to.do?:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"

# This rule is a catch all
[[redirects]]
  from = "/*"
  to = "https://dev16718.service-now.com/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"